In [35]:
def conv(A,F):
    a = A.shape
    f = F.shape
    high = a[0] - f[0] +1;
    width = a[1] - f[1] +1;
    
    O = np.zeros([high,width]);
    for i in range(high):
        for m in range(width):
            for l in range(f[0]):
                for p in range(f[1]):
                    O[i][m] += F[l][p] * A[i+l][m+p];
    return O;

In [36]:
import numpy as np
A = np.array([[10,5,20,20,20],[10,5,20,20,20],[10,5,20,20,20],[10,5,20,20,20],[10,5,20,20,20]],dtype = int);

In [ ]:
print(A.shape);

In [ ]:
B = np.array([[-1,1],[0,5]],dtype = int);

In [ ]:
O = conv(A,B);

In [ ]:
print(O);
print(O);

# 矩阵方法计算

In [37]:
def im2col(mtx,block_size):
    mtx_shape = mtx.shape
    sx = mtx_shape[0] - block_size[0] + 1;
    sy = mtx_shape[1] - block_size[1] + 1;
    result = np.empty((block_size[0] * block_size[1],sx * sy));
    for i in range(sy):
        for j in range(sx):
            result[:,i*sx+j] = mtx[j:j+block_size[0],i:i+block_size[1]].ravel(order='F');
    return result;
def col2im(mtx,image_size,block_size):
    p,q = block_size;
    sx = image_size[0] - p +1;
    sy = image_size[1] - q +1;
    result = np.empty(image_size);
    weight = np.zeros(image_size);
    col =0;
    for i in range(sy):
        for j in range(sx):
            result[j:j +p,i:i+q] +=mtx[:,col].reshape(block_size,order='F');
            weight[j:j+p,i:i+q] += np.ones(block_size);
            col+=1;
    return result/weight;

In [43]:
A = np.array([[1,2,3],[4,5,6],[7,5,8]],dtype = int);
B = np.array([[-1,1],[0,5]],dtype = int);
A1 = im2col(A,(2,2));
B1 = im2col(B,(1,1));
print(A1)
print(B1);
C = np.dot(B1,A1);
print(C);
#C1 = col2im(C,(2,2),(1,1));
C2 = conv(A,B);
#print(C1);
print(C2);

[[1. 4. 2. 5.]
 [4. 7. 5. 5.]
 [2. 5. 3. 6.]
 [5. 5. 6. 8.]]
[[-1.  0.  1.  5.]]
[[26. 26. 31. 41.]]
[[26. 31.]
 [26. 41.]]
